modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="universalarmor"
version="1.0.0"
displayName="Universal Armor"
authors="TheCascadian"
description='''
Craft armor dynamically out of absolutely anything in the game! Full cross-mod compatibility with no custom registry bloat.
'''

[[dependencies.universalarmor]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.universalarmor]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"